services:
  db:
    image: postgres:16.3
    container_name: librarydb
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - pgdata_librarydb:/var/lib/postgresql/data
    networks:
      - library-network
    healthcheck:
      # garantir que o banco está pronto antes do pgAdmin subir
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_librarydb
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASS}
    ports:
      - "8080:80"
    networks:
      - library-network
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./config_pgadmin:/var/lib/pgadmin

networks:
  library-network:
    driver: bridge

volumes:
  pgdata_librarydb: