services:
  db:
    image: postgres:16.3
    container_name: pg_portfolio
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=libraryapi
    ports:
      - "5432:5432"
    volumes:
      - pgdata_portfolio:/var/lib/postgresql/data
    networks:
      - portfolio-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d portfolio_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_portfolio
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8080:80"
    networks:
      - portfolio-network
    depends_on:
      db:
        condition: service_healthy

networks:
  portfolio-network:
    driver: bridge

volumes:
  pgdata_portfolio:
