spring:
    aplication:
        name: libraryapi
    datasource:
        url: jdbc:postgresql://localhost:5433/library
        username: admin
        password: senhaSuperSegura123
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true